### ISSUE TITLE
nuget package doesn't install

### ISSUE THREAD

**Issue by butlerpeter** [adam8797/EasyScintilla#1]
Following the readme and trying to install from nugget fails. I get the below in the package manager console...

`Installing 'EasyScintilla 1.0.1'.
You are downloading EasyScintilla from Adam Schiavone, the license agreement to which is available at https://github.com/adam8797/EasyScintilla/blob/master/LICENSE. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'EasyScintilla 1.0.1'.
Adding 'EasyScintilla 1.0.1' to WindowsFormsApplication1.
Uninstalling 'EasyScintilla 1.0.1'.
Successfully uninstalled 'EasyScintilla 1.0.1'.
Install failed. Rolling back...
Install-Package : Could not install package 'EasyScintilla 1.0.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.1', but the package does not contain any assembly 
references or content files that are compatible with that framework. For more information, contact the package author.`

I've gotten round it for now by cloning and building locally. Seems to be a really nice little control so far.

Also found a couple of instances of a typo in PowershellStyler.cs - HereCharcter instead of HereCharacter

**Comment by adam8797** [comment]
I've re-targeted EasyScintilla to .NET 4.0. You were getting that error because your project was using .NET 4.5.1, but EasyScintilla was built with .NET 4.6.1. You can check for an updated NuGet package shortly.

As for the spelling, those mistakes are part of Scintilla.NET, not this project.

**Comment by butlerpeter** [comment]
Thanks for the fix. Updated package works great.
