### ISSUE TITLE
SimpleEditor control missing from the toolbox 

### ISSUE THREAD

**Issue by jeyami** [adam8797/EasyScintilla#2]
I'm not able to see the SimpleEditor Component after installing EasyScintilla v1.02. (the installation was successful)

I'm using Visual Studio Community 2015 Update 3 and jacobslusser.ScintillaNet v3.6.3

Thanks, 
Jay

**Comment by adam8797** [comment]
That's strange. 

First things first make sure to build the project first. The designer only shows new components after a build.

**Comment by akmlvl** [comment]
yeah me it dosen't show up in the control box

**Comment by adam8797** [comment]
Yeah something funky is going on. I'm looking into it.

**Comment by psaxton** [comment]
I am able to replicate this issue. Receiving an error when trying to add the component to the toolbox:
`Unable to load 'C:\...\packages\EasyScintilla.1.0.2\lib\net40\EasyScintilla.dll' or one of its dependencies'`

![easyscintilla load error](https://user-images.githubusercontent.com/15615330/27491302-0e2075ee-57ff-11e7-9f74-1bc903076afa.png)

**Comment by adam8797** [comment]
Yeah, I've been digging around on and off for this. There is some issue with the designer not loading all the dependencies needed correctly. I'll post back if I figure out a solution.

For now you can use the SimpleEditor control from code. Its just the designer that's not having a good time.

**Comment by psaxton** [comment]
Hope that helps :)

**Comment by adam8797** [comment]
Looks like that update helped.

I still had to manually add the controls to the Toolbox, but at least now it let me do it. I'll add the documentation to the readme on how to do this.

**Comment by psaxton** [comment]
Keep up the good work. For me, it turned a task of converting a textbox to a scintilla control from 2 hours to 10 minutes.
