### ISSUE TITLE
Powershell lexer does not interpret quotes escaping

### ISSUE THREAD

**Issue by hellon8** [adam8797/EasyScintilla#4]
Powershell lexer ignores quote escaping (`) , it was resolved in the newer version of ScintillaNET.

**Comment by adam8797** [comment]
Will update and republish as soon as I'm able.

**Comment by adam8797** [comment]
@hellon8 What version of ScintillaNET are you referencing? 3.6.3 is currently the latest?

**Comment by adam8797** [comment]
No reply. Closing. Reopen if you still have an issue.
