### ISSUE TITLE
There are no components in...

### ISSUE THREAD

**Issue by Bonejob** [adam8797/EasyScintilla#9]
when navigating to add the toolbox control for the EasyScintilla it is returning an error saying "there are not compnents in ...\packages\EasScintilla.1.0.4\lib\net40\EasyScintilla.dll"

Added and removed the package via package manager and it did not fix the problem.

**Comment by Bonejob** [comment]
I will look into it further, it seems to be in the object explorer so I know the package is loaded. If I figure it out I will leave a post to this thread.

**Comment by adam8797** [comment]
Sounds good. If you find a code change is needed, send me a pull request and I’ll merge it.
